name: Code Quality
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra code-quality

      - name: Run pre-commit with debug
        run: |
          echo "Running pre-commit hooks with verbose output..."
          uv run pre-commit run --all-files --verbose
          if [ $? -ne 0 ]; then
            echo "Pre-commit failed. Showing git status:"
            git status
            echo "Showing git diff:"
            git diff
            exit 1
          fi
